### ISSUE TITLE
Ability to define file to open

### ISSUE THREAD

**Issue by pdwonline** [htmltiger/config-editor-card#33]
Would be powerfull to be able to specify the file to open in the configuration for a specific instance..
for exaple:

```
type: custom:config-editor-card
options: 
  file: myfile.yaml            # File to load (optional)
  file-type: yaml              # Define file type, hides file type selector (optional)
  file-selector: false        # Hide file selector when false (optional)
  read-only: false            # Remove save button when false
  basic-editor: false        # Set basic editor mode

```
